### ISSUE TITLE
Question about Dexcom SHARE Credentials

### ISSUE THREAD

**Issue by Axel-Erfurt** [Narmis-E/DexViewer#1]
I just helped someone install it remotely. What is meant by “Dexcom SHARE Credentials”?
Is an account with Dexcom necessary?
Thanks

If I type anything, I get

```
TypeError: Dexcom.__init__() takes 1 positional argument but 4 were given
```

**Comment by Narmis-E** [comment]
Hey, 
I just sent an email to your friend, explaining the process of retrieving the Dexcom Share account details. 

Upon creation of your Dexcom account, you need to enter a username and password. This is used for signing into various other clients, such as Dexcom Clarity, and for programs which use the Dexcom Share API, such as Dexviewer.

[Here](https://nightscout.github.io/troubleshoot/dexcom_bridge/) explains it a bit better. 

The Dexcom Share Service is hosted by Dexcom, which allows anyone with a dexcom account to retrieve that account's blood glucose data, usually for family members to keep track of their relatives blood sugar levels. 
Dexviewer is purely designed to pull data from this service through the use of [pydexcom](https://github.com/gagebenne/pydexcom) which requires the username and password of the account, which is found inside the Dexcom app.

I apologise for not explaining this very well in the README, I assumed that most people already knew about Dexcom Share.

Let me know if there's anything else I can help with,
Although I'm not really maintaining this on a frequent basis anymore.

Thanks 😊

**Comment by Axel-Erfurt** [comment]
Thank you,
are you using a Gtk4 version > 4.10?

**Comment by Narmis-E** [comment]
No, it is still on GTK 4.0 I'm afraid. There might be some breaking changes... I'm not really sure

**Comment by Axel-Erfurt** [comment]
I thought it because Gtk.AlertDialog was introduced in GTK 4.10.

**Comment by Narmis-E** [comment]
Hmm, I appear to be using it with 4.0: 

```
gi.require_version('Gtk', '4.0')
...
def on_ok_clicked(self, button):
        self.username = self.username_entry.get_text()
        self.password = self.password_entry.get_text()
        self.ous = str(self.ous_check.get_active())
        if not self.username or not self.password:
            dialog = Gtk.AlertDialog()
            dialog.set_message("Invalid Credentials")
            dialog.set_detail("Credentials cannot be empty.")
            dialog.set_buttons(["OK"])
            dialog.show()
```

I see what you mean, on the GTK docs, it does list it as a feature of 4.1..... not really sure what's happened here.
